version: "3.9"
services:
  mysql:
    image: mysql
    container_name: laravel-empresa
    ports:
      - "23104:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=gabi
      - MYSQL_PASSWORD=gabi
      - MYSQL_DATABASE=empresas
      - MYSQL_ROOT_PASSWORD=root

  pymyadmin:
    image: phpmyadmin
    ports:
      - "8800:80"
    depends_on:
    - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
